In [29]:
import torch
import math

In [30]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [31]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [32]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [33]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [34]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [35]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [36]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [37]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.4004, 0.9877, 0.0352, 0.0905],
        [0.4485, 0.8740, 0.2526, 0.6923]])
tensor([[0.8008, 1.9755, 0.0705, 0.1810],
        [0.8971, 1.7480, 0.5051, 1.3846]])


In [ ]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.6545, 0.4144],
         [0.0696, 0.4648],
         [0.4491, 0.6265]],

        [[0.6545, 0.4144],
         [0.0696, 0.4648],
         [0.4491, 0.6265]],

        [[0.6545, 0.4144],
         [0.0696, 0.4648],
         [0.4491, 0.6265]],

        [[0.6545, 0.4144],
         [0.0696, 0.4648],
         [0.4491, 0.6265]]])
tensor([[[0.9411, 0.9411],
         [0.4922, 0.4922],
         [0.5461, 0.5461]],

        [[0.9411, 0.9411],
         [0.4922, 0.4922],
         [0.5461, 0.5461]],

        [[0.9411, 0.9411],
         [0.4922, 0.4922],
         [0.5461, 0.5461]],

        [[0.9411, 0.9411],
         [0.4922, 0.4922],
         [0.5461, 0.5461]]])
tensor([[[0.5396, 0.3053],
         [0.5396, 0.3053],
         [0.5396, 0.3053]],

        [[0.5396, 0.3053],
         [0.5396, 0.3053],
         [0.5396, 0.3053]],

        [[0.5396, 0.3053],
         [0.5396, 0.3053],
         [0.5396, 0.3053]],

        [[0.5396, 0.3053],
         [0.5396, 0.3053],
         [0.5396, 0.3053]]])


In [ ]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(4, 3)    # dimensions must match last-to-first

c = a * torch.rand(   2, 3) # both 3rd & 2nd dims different

d = a * torch.rand((0, ))   # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [ ]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.5951, 0.1461, 0.4382, 0.1866],
        [0.4602, 0.2551, 0.4715, 0.9238]])
tensor([[-0., 1., 1., -0.],
        [1., 1., 1., -0.]])
tensor([[-1.,  0.,  0., -1.],
        [ 0.,  0.,  0., -1.]])
tensor([[-0.5000,  0.1461,  0.4382, -0.1866],
        [ 0.4602,  0.2551,  0.4715, -0.5000]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.2138, 0.5395],
        [0.3686, 0.4007]])
tensor([[0.6414, 1.6186],
        [1.1057, 1.2021]])
torch.return_types.svd(
U=tensor([[-0.7309, -0.6825],
        [-0.6825,  0.7309]]),
S=tensor([2.3475, 0.4339]),
V=tensor([[-0.5212,  0.8535],
        [-0.8535, -0.5212]]))


In [ ]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [ ]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.4567, 0.0649],
        [0.6677, 0.7826]])

After adding:
tensor([[1.4567, 1.0649],
        [1.6677, 1.7826]])
tensor([[1.4567, 1.0649],
        [1.6677, 1.7826]])
tensor([[0.4567, 0.0649],
        [0.6677, 0.7826]])

After multiplying
tensor([[0.2086, 0.0042],
        [0.4459, 0.6125]])
tensor([[0.2086, 0.0042],
        [0.4459, 0.6125]])


In [ ]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c), old_id    # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c), old_id    # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.5421, 1.0851],
        [0.3519, 0.7800]])
tensor([[0.9004, 0.3995],
        [0.6324, 0.9464]])


In [ ]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# manipulate tensor's shape

a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

c = torch.rand(1, 1, 1, 1, 1)
print(c)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])
tensor([[[[[0.4977]]]]])


In [ ]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[2.0716e-01, 3.6112e-01, 5.8199e-01, 9.7356e-01, 1.6555e-02, 1.6518e-01,
         7.6789e-01, 3.0665e-02, 8.1988e-01, 4.6275e-01, 7.8319e-01, 2.2328e-04,
         8.0810e-01, 6.2075e-01, 3.0783e-01, 9.6298e-01, 3.3805e-01, 8.1330e-01,
         9.7368e-01, 5.9730e-01]])
torch.Size([20])
tensor([2.0716e-01, 3.6112e-01, 5.8199e-01, 9.7356e-01, 1.6555e-02, 1.6518e-01,
        7.6789e-01, 3.0665e-02, 8.1988e-01, 4.6275e-01, 7.8319e-01, 2.2328e-04,
        8.0810e-01, 6.2075e-01, 3.0783e-01, 9.6298e-01, 3.3805e-01, 8.1330e-01,
        9.7368e-01, 5.9730e-01])
torch.Size([2, 2])
torch.Size([2, 2])


In [38]:
a =     torch.ones(4, 3, 2)
c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

tensor([[[0.2024, 0.2024],
         [0.5731, 0.5731],
         [0.7191, 0.7191]],

        [[0.2024, 0.2024],
         [0.5731, 0.5731],
         [0.7191, 0.7191]],

        [[0.2024, 0.2024],
         [0.5731, 0.5731],
         [0.7191, 0.7191]],

        [[0.2024, 0.2024],
         [0.5731, 0.5731],
         [0.7191, 0.7191]]])
torch.Size([3, 1])
tensor([[[0.4067, 0.4067],
         [0.7301, 0.7301],
         [0.6276, 0.6276]],

        [[0.4067, 0.4067],
         [0.7301, 0.7301],
         [0.6276, 0.6276]],

        [[0.4067, 0.4067],
         [0.7301, 0.7301],
         [0.6276, 0.6276]],

        [[0.4067, 0.4067],
         [0.7301, 0.7301],
         [0.6276, 0.6276]]])
